name: CPU Unit Test

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: unit-test${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 20
      matrix:
        os: [ubuntu-22.04]
        python-version: [3.10.16]
    steps:
      - name: Cache Python Packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Fetch S3Tokenizer
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
      - name: Install S3Tokenizer Dependencies
        run: |
          set -eux
          sudo apt update && sudo apt install -y ffmpeg  libsox-dev libsndfile1
          pip install -e .
      - name: Run Pytest
        run: |
          set -eux
          pip install pytest onnxruntime
          pytest --version
          PYTHONPATH="${PYTHONPATH:-}:$(pwd)" pytest test/ -q
          if [ $? != 0 ]; then exit 1; fi
